name: Deploy to Public Branch

on:
  push:
    branches:
      - main
  workflow_dispatch: true

jobs:
  sync-to-public:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0